global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  # Chatbot application metrics
  - job_name: 'chatbot'
    static_configs:
      - targets: ['chatbot-prod:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node.js application metrics
  - job_name: 'nodejs'
    static_configs:
      - targets: ['chatbot-prod:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 15s

  # System metrics
  - job_name: 'system'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s
